### ISSUE TITLE
”issueベースの開発”レビュー依頼

### ISSUE THREAD

**Issue by agc15000** [agc15000/fuku_log_kaihatsu#53]

**Comment by agc15000** [comment]
### 概要
自身の所有する服の購入記録や使用記録、経年変化の記録をつけることで、服への愛情（価値）を増やすことができる。
自身の服の記録だけでなく他のユーザーの記録を閲覧することや、メッセージ、コメント、いいね機能などによるユーザー同士のコミュニケーションをとることができる、更に自身の服の記録を他のユーザーに譲ることができる。

### 実装予定機能MVP時
- **基本機能**
    - [ ] ユーザー登録
    - [ ]  ログイン
    - [ ]  パスワード変更
- **洋服の記録**: ユーザーは自分の洋服を画像とともに記録できる
    - [ ]  画像保存
    - [ ] タグ付け（デニム、冬、夏、デートなど）
    - [ ] 洋服に関するエピソードの記録（テキストや写真で）
- **洋服の共有**: ユーザーは記録した洋服を他のユーザーと共有できる
    - [ ] 所有者ごとの検索
    - [ ] カテゴライズやタグによる検索
    - [ ] お気に入り登録
    - [ ] 譲る機能（自身の洋服の記録を任意の相手に渡す）
    - [ ] フォローユーザーの記録のタイムライン表示
- **コミュニケーション**: ユーザー間でコミュニケーションを取ることができる
    - [ ] メッセージ機能
    - [ ] コメント機能
    - [ ] フォロー機能

**Comment by Tsuchiya2** [comment]
ご提出ありがとうございます。
概ね良いかと思います。LGTMです。

---

以下はMVP後でも良いかと思ったカードです。

- タグ付け機能
- お気に入り機能
- メッセージ機能
- コメント機能
- タイムライン機能
- フォロー・フォロワー機能
- プロフィール
- アイテムを譲る機能
- 洋服タグ一覧
- タイムライン画面
- いいね一覧画面
- フォロワー一覧画面
- プロフィール画面
- 無限スクロール
- フォロー一覧画面
- 一覧表示関連画面のSPA化
- メッセージ一覧画面

Herokuへのデプロイはrails new直後にしましょう。

**Comment by agc15000** [comment]
ありがとうございます。
MVP時の機能は絞って行こうと思います。
デプロイはrails new直後に行うようにします。
