### ISSUE TITLE
MVP(β版)レビュー

### ISSUE THREAD

**Issue by agc15000** [agc15000/fuku_log_kaihatsu#63]
### サービス名
　アイテムレコード
 ### サービスURL
　https://quiet-island-51281-91008ce0b258.herokuapp.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- 基本機能
 - [ ] ユーザー登録
 - [ ] ログイン
 - [ ] パスワード変更
- 洋服の記録: ユーザーは自分の洋服を画像とともに記録できる
 - [ ] 画像保存
 - [ ] タグ付け（デニム、冬、夏、デートなど）
 - [ ] 洋服に関するエピソードの記録（テキストや写真で）
- 洋服の共有: ユーザーは記録した洋服を他のユーザーと共有できる
 - [ ] 所有者ごとの検索
 - [ ] カテゴライズやタグによる検索
 - [ ] お気に入り登録
 - [ ] 譲る機能（自身の洋服の記録を任意の相手に渡す）
 - [ ] フォローユーザーの記録のタイムライン表示
 - [ ] タイムライン（他ユーザーの記録：時系列順にランダム）
- コミュニケーション: ユーザー間でコミュニケーションを取ることができる
 - [ ] メッセージ機能
 - [ ] コメント機能
 - [ ] フォロー機能

## READMEレビュー時に実装予定かつ、現時点で実装できたもの
- 基本機能
 - [ ] ユーザー登録
 - [ ] ログイン
- 洋服の記録: ユーザーは自分の洋服を画像とともに記録できる
 - [ ] 画像保存
 - [ ] タグ付け（デニム、冬、夏、デートなど）
 - [ ] 洋服に関するエピソードの記録（テキストのみ）
- 洋服の共有: ユーザーは記録した洋服を他のユーザーと共有できる
 - [ ] 所有者ごとの検索

## READMEレビュー時に実装予定かつ、現時点で実装できていないもの
- 洋服の共有: ユーザーは記録した洋服を他のユーザーと共有できる
 - [ ] カテゴライズやタグによる検索
 - [ ] お気に入り登録
 - [ ] 譲る機能（自身の洋服の記録を任意の相手に渡す）
 - [ ] フォローユーザーの記録のタイムライン表示
 - [ ] タイムライン（他ユーザーの記録：時系列順にランダム）
- コミュニケーション: ユーザー間でコミュニケーションを取ることができる
 - [ ] メッセージ機能
 - [ ] コメント機能
 - [ ] フォロー機能
- UI/UX関連
 - [ ] ページの装飾※READMEに特に記載はないですが、当然にして必要ですので記載しました

## READMEレビュー時から変更した機能
 - [ ] アイテム名による検索機能追加

お手数ですがご確認のほど、よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
